# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afectacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('inicio', models.TimeField()),
                ('termino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=300)),
                ('company_short', models.CharField(max_length=300)),
                ('pais_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad_address', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_address', models.CharField(blank=True, max_length=30, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=500)),
                ('sedcard', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('mod', 'Modelo'), ('fot', 'Fotografo'), ('mak', 'Make Up'), ('sty', 'Styling'), ('rhh', 'Recursos Humanos'), ('otr', 'Styling')], default='mod', max_length=3)),
            ],
            options={
                'verbose_name': 'Pesona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('comment', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField()),
                ('fecha_ejecucion', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apli.Client')),
            ],
        ),
        migrations.AddField(
            model_name='afectacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apli.Persona'),
        ),
        migrations.AddField(
            model_name='afectacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apli.Proyecto'),
        ),
    ]
