# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Pesona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.AddField(
            model_name='client',
            name='ciudad_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='codigo_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pais_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
