# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0002_auto_20170825_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='statut',
            field=models.CharField(choices=[('project', 'project'), ('confirmed', 'confirmed'), ('realized', 'realized'), ('acquitted', 'acquitted'), ('canceled', 'canceled')], default='angebot', max_length=9),
        ),
    ]
