# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0006_auto_20170828_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='statut',
            field=models.CharField(choices=[('modell', 'Modelo'), ('Photograph', 'Fotografo'), ('Make Up', 'Make Up'), ('Styling', 'Styling'), ('Rrhh', 'Recursos Humanos'), ('verschieden', 'Otro')], default='Modell', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='sort',
            field=models.CharField(choices=[('Angebot', 'angebot'), ('Auftrag', 'aufttrag'), ('Job', 'job')], default='Angebot', max_length=8),
        ),
    ]
