# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0007_auto_20170828_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
    ]
