# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0008_auto_20170828_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
    ]
