# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0009_auto_20170829_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'Cost', 'verbose_name_plural': 'Costs'},
        ),
    ]
