# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0010_auto_20170830_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaire',
            options={'verbose_name': 'Horaire', 'verbose_name_plural': 'Horaires'},
        ),
    ]
